### ISSUE TITLE
Renew the issue template to use the latest

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#328]
### Issue Type

- [ ] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [x] Documentation

### Description

We see the following warning when visiting [the GitHub issue template](https://github.com/slackapi/java-slack-sdk/blob/master/.github/issue_template.md) we currently use.

>You are using an old version of issue templates. Please update to the new issue template workflow. Learn more

* https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
This is already done.
