### ISSUE TITLE
Handling interaction payloads - responding Ack to Slack

### ISSUE THREAD

**Issue by Pravez** [slackapi/java-slack-sdk#330]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [x] Documentation

### Description

I am building a server sending messages to a slack application. However, some messages contain BlockElements and especially Buttons. When clicking on buttons with an URL, the browser opens up but also a warning sign appears on the left of the button. According to the documentation it is perfectly justified by the fact that my server did not answer a 200 Response, so Slack does not know how has been interpreted the payload sent to the server.

What I am searching for is just an example of how to handle this kind of error. I looked everywhere and could not find a clear solution. I supposed it was about BlockActionsHandler located in the lightning package, but I cannot use it. As I understood it is supposed to be an endpoint defined in a @RestController, but I was unable to find how to build this component.

Thank you for your help ...

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.
