### ISSUE TITLE
Group from SCIM is not according to the actual response

### ISSUE THREAD

**Issue by TarasPavliuchyn** [slackapi/java-slack-sdk#409]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description
`com.slack.api.scim.SCIMClient#searchUsers()` returns users with groups where all fields are empty.  
The problem is in wrong filed names in `com.slack.api.scim.model.Group` . Actual HTTP response looks like (from slackHttpClient): 
> {
 // skipped text
    "groups": [{
      "value": "XXXXXXX",
      "display": "Awesome Group"
    }]
  }]
}

 So `Gson` can't parse it to `com.slack.api.scim.model.Group` correctly. As a result all fields are null.

The issue is reproducible in:
* Module Version: com.slack.api:slack-api-client:1.0.0-M1 and above
* JDK Version: openjdk version "1.8.0_222"

The steps to reproduce are:
1. Run `com.slack.api.scim.SCIMClient#searchUsers()`for users that assigned to the group.

The expected result is:
At least I expect to see 'display' attribute.

The actual result is:
All fields in Group are empty.

**TODO**:
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@TarasPavliuchyn I've fixed the bug by #411. I'm going to release a new patch version within a few hours. Thanks for reporting the issue and I'm sorry for the inconvenience.

**Comment by seratch** [comment]
Thank you very much again for taking the time to report this. A new version - 1.0.2 is out now. Please try it out when you have a chance.

**Comment by TarasPavliuchyn** [comment]
Thank you for the fast fix.
