### ISSUE TITLE
ctx ack with Chinese text

### ISSUE THREAD

**Issue by Jian-Min-Huang** [slackapi/java-slack-sdk#429]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [ ] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

**TODO**:
This is the official example
```java
app.command("/hello", (req, ctx) -> {
    return ctx.ack(":wave: Hello!");
});
```
but if I add some Chinese text
```java
app.command("/hello", (req, ctx) -> {
    return ctx.ack(":wave: Hello! 哈囉");
});
```
it will return question mark
![](https://github.com/Jian-Min-Huang/tech-note/blob/master/images/slack-java-sdk-pr.jpg?raw=true)

so I try to explore the source code, I guess the problem is about contentType
I try to modify my code like below and it works
application/json -> application/json; charset=utf-8
```java
app.command("/hello", (req, ctx) -> {
     return Response.builder().statusCode(200).contentType("application/json; charset=utf-8").body(JsonOps.toJsonString(SlashCommandResponse.builder().text(":wave: Hello! 哈囉").build())).build();
});
```
but this style may be too long to read
so I add a pull request is about this issue, please help 😆

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@Jian-Min-Huang Thanks for reporting (and making a PR too!) this issue. Your PR #430 has addressed the issue. Let me close this issue now. I'm be releasing a new patch version (1.0.6) within a few days.
