### ISSUE TITLE
Question: how to open a modal view in Bolt for Java?

### ISSUE THREAD

**Issue by sunny952** [slackapi/java-slack-sdk#433]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [X] Question
- [ ] Documentation

### Description

I want to pen a model view. 
I copy a sample in slack java sdk sit.

```java
 return view(view -> view
   .callbackId("meeting-arrangement")
   .type("modal")
   .notifyOnClose(true)
   .title(viewTitle(title -> title.type("plain_text").text("Meeting Arrangement").emoji(true)))
   .submit(viewSubmit(submit -> submit.type("plain_text").text("Submit").emoji(true)))
   .close(viewClose(close -> close.type("plain_text").text("Cancel").emoji(true)))
       .blocks(asBlocks(
             section(section -> section
                   .blockId("category-block")
                   .text(markdownText("Select a category of the meeting!"))
                   .accessory(staticSelect(staticSelect -> staticSelect
                     .actionId("category-selection-action")
                     .placeholder(plainText("Select a category"))
                     .options(asOptions(
                       option(plainText("Customer"), "customer"),
                       option(plainText("Partner"), "partner"),
                       option(plainText("Internal"), "internal")
                     ))
                   ))
                 ),
                 input(input -> input
                   .blockId("agenda-block")
                   .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
                   .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
                 )
               )));
```

sometimes return invalid arguments ,sometimes is successful,but  I can not see model .
I check log then sometimes print out success message, sometimes print out invalid arguments.  I can not see model in slack when system print out success message. I want to know how to open a model in slack

---
(only for a bug report)

The issue is reproducible in:
* Module Version: 1.0.2
* JDK Version: 1.8

The steps to reproduce are:
1.
2.
3.

The expected result is:
   I send a slash command, then open a model.

The actual result is:
 see nothing. or operations timeout

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@sunny952 👋 The complete working example for the document page is available here. 
https://github.com/slackapi/java-slack-sdk/blob/v1.0.6/bolt/src/test/java/test_locally/docs/ModalsTest.java

Can you check the difference? If you see something unclear, I'm happy to help you out (share details and your code if possible then).

**Comment by sunny952** [comment]
i  missed  privateMetadata https://hooks.slack.com/actions/T1ABCD2E12/330361579271/0dAEyLY19ofpLwxqozy3firz   I want to know this responseurl is necessary?

**Comment by seratch** [comment]
It's not necessary if you don't need to store some data across modals. It's just an example.

**Comment by sunny952** [comment]
hi I want to know how does rich_text_quote and rich_text_preformatted
work?  do you have an example?

**Comment by seratch** [comment]
@sunny952 
You may see those blocks when a user posted a message using the WYSIWYG mode in Slack. But those blocks are not supposed to be used in Slack API calls. Refer to the following document for details.
https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less

You may have more questions. You can ask general questions like this at [Bot Developer Hangout workspace](https://community.botkit.ai/) and our developer support agents.

As a maintainer of this project, I would like to keep this place used only for feedback, bug reports, and questions about the Java SDK. Let me close this issue now. I'd appreciate it if you could understand this.

**Comment by sunny952** [comment]
sure
