### ISSUE TITLE
Use Bolt for Sign in with Slack?

### ISSUE THREAD

**Issue by timrourke** [slackapi/java-slack-sdk#488]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I'm curious about using Bolt to manage OAuth2 flows for both:
- installing an application into a third party's Slack workspace
- _and_ for using Slack for "Sign in with Slack" functionality

What I see when completing the OAuth2 flow for installing applications is that it is in fact possible to include scopes for both an application and a user, and I can see that when returning to my configured callback endpoint, I receive a payload containing tokens for both the user, _and_ the bot.

However, the default behavior of Bolt is to then make a request to the [auth.test](https://api.slack.com/methods/auth.test) endpoint _for the bot only_, and automatically proceeds to (correctly) install the app into the workspace.

This makes sense to me; Bolt is designed for building Slack apps, not for helping solve the more general problem of federated application authentication via OAuth2. However, I see a lot of components available to me in Bolt that would be helpful for generic "Sign in with Slack" behavior.

Is there a recommended approach to using Bolt in this dual-purpose way? *Or am I perhaps overlooking some configuration that would support both strategies out of the box?*

If there isn't a "blessed" approach for doing this kind of thing, the approach I'm considering is to cobble together an OAuth2 flow request handler for "Sign in with Slack" out of the provided components, like [the FileOAuthStateService](https://github.com/slackapi/java-slack-sdk/blob/e0efcbf9d55c8ac5c6a7cce149761e338c9286f8/bolt/src/main/java/com/slack/api/bolt/service/builtin/FileOAuthStateService.java) based on the existing Bolt OAuth stuff. Does that make sense, or would I be better off implementing something from scratch?

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
>Is there a recommended approach to using Bolt in this dual-purpose way? Or am I perhaps overlooking some configuration that would support both strategies out of the box?

If the intention of the "dual-purpose" here is reusing POST `/slack/events` endpoint for handling incoming requests from other services, my short answer is no. The endpoint the built-in middleware such as RequestVerification, MultiTeamsAuthorization are enabled is supposed to handle only incoming requests from the Slack API server. 

So, I recommend having other URLs for any other purposes. For handling completely different types of requests in another path, there are two recommended ways to go.

* Adding extra endpoints using the `endpoint` method
  * [Sample app that renders OAuth completion/error pages](https://github.com/slackapi/java-slack-sdk/blob/v1.0.10/bolt-kotlin-examples/src/main/kotlin/examples/oauth_flow_v2/v2_app.kt#L35-L37)
  * If your runtime allows `App` to have more path to handle, this is handy and simple for management
* Embedding Bolt app as part of larger web app
  * [Bolt app as a controller in Spring Boot app](https://github.com/slackapi/java-slack-sdk/blob/v1.0.10/bolt-spring-boot-examples/src/main/java/example/SlackAppController.java)
  * This is more flexible and you don't have any limitations in this way

Either way, you can freely reuse any modules offered by Bolt as long as they're public interface/classes (I guess this is your main question here). 

One minor advice specific to `OAuthStateService` is you can override [the `getSessionCookieName` method](https://github.com/slackapi/java-slack-sdk/blob/v1.0.10/bolt/src/main/java/com/slack/api/bolt/service/OAuthStateService.java#L20-L23) to have different names for several purposes.

**Comment by timrourke** [comment]
Thanks as always, @seratch! Great advice, appreciate the tip about cookie naming.
