### ISSUE TITLE
files list is absent in MessageEvent of MessagePayload to support attachments in message event

### ISSUE THREAD

**Issue by Hariprasad-Ramakrishnan** [slackapi/java-slack-sdk#494]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

**TODO**:
When a user adds attachments, this comes as `files` in the slack message event. But `files` field is absent in `MessageEvent` of the sdk. 

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Hariprasad-Ramakrishnan** [comment]
@seratch , Please consider this PR : https://github.com/slackapi/java-slack-sdk/pull/495

**Comment by teamstand-rishabh** [comment]
can you update the same in maven repo

**Comment by seratch** [comment]
We'll be releasing a new version early next week.
