### ISSUE TITLE
Getting NoSuchMethodError kotlin.collections.ArraysKt.copyInto Exception

### ISSUE THREAD

**Issue by AbhiInfy** [slackapi/java-slack-sdk#518]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

**TODO**:
(Describe your issue here)
Getting NoSuchMethodError kotlin.collections.ArraysKt.copyInto([B[BIII) while starting application
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    okio.Segment.writeTo(Segment.kt:169)

The following method did not exist:

    kotlin.collections.ArraysKt.copyInto([B[BIII)[B

The method's class, kotlin.collections.ArraysKt, is available from the following locations:

    jar:file:/C:/Users/**/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar!/kotlin/collections/ArraysKt.class

It was loaded from the following location:

    file:/C:/Users/**/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of kotlin.collections.ArraysKt

I am trying to run com.slack.api.Slack application by IntelliJ IDE in Java to send the message in slack. I am using Java 1.8 and SpringBoot
---
(only for a bug report)

**TODO**:
If this is a bug report, filling out the following details about bugs will help us solve your issue sooner.

The issue is reproducible in:
* Module Version: **TODO**: x.y.z
* JDK Version: **TODO**: Run `java -version` and pates the result here
* OS Version etc: **TODO**: if the issue happens only with specific OS

The steps to reproduce are:
1.
2.
3.

The expected result is:
**TODO**: What you expected to happen

The actual result is:
**TODO**: What actually happened
---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@AbhiInfy 
> NoSuchMethodError kotlin.collections.ArraysKt.copyInto([B[BIII)

The error message indicates your build settings (or IDE settings) have some binary-compatibility issue with the Kotlin standard library.

> kotlin-stdlib/1.2.71

This SDK requires okhttp library, which depends on Kotlin 1.3.x. Try Kotlin 1.3.x instead.

**Comment by seratch** [comment]
Let me know if you need further help here. Please allow me to close this issue after waiting for your response for a few more days.

**Comment by seratch** [comment]
> Please allow me to close this issue after waiting for your response for a few more days.

Closing now. Please feel free to reopen if needed.

**Comment by lwl5219** [comment]
> This SDK requires okhttp library, which depends on Kotlin 1.3.x. Try Kotlin 1.3.x instead.

I replace the version with **1.3.70**. It works for me.

```
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>4.9.1</version>
</dependency>
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.3.70</version>
</dependency>
```
