### ISSUE TITLE
How to send a DM message using Java sdk

### ISSUE THREAD

**Issue by AbhiInfy** [slackapi/java-slack-sdk#530]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I want to send DM to the User and would need to follow the below steps:

1. Lookup user ID from email: https://api.slack.com/methods/users.lookupByEmail

2. Open DM with user: https://api.slack.com/methods/conversations.open

3. Send a message to the DM: https://api.slack.com/methods/chat.postMessage

4. May need to close the DM afterwards: https://api.slack.com/methods/conversations.close

All the above steps need to integrate into my web application, which is built in Java and Spring Boot. So how to achieve all these steps in Java. Kindly provide code snippet.

Below is my code snippet so far to send message to the channel:

```java
Slack slack = Slack.getInstance();
public void sendMessage(String slackContent, String emloyeeName) {
    List<LayoutBlock> message = new ArrayList();
    message.add(SectionBlock
        .builder()
        .text(MarkdownTextObject
            .builder()
            .text("Dear "+emloyeeName+"")
            .build())
        .build());
    message.add(SectionBlock
        .builder()
        .text(MarkdownTextObject
            .builder()
            .text("Please fill out the survey at:")
            .build())
        .build());
    message.add(SectionBlock
        .builder()
        .text(MarkdownTextObject
            .builder()
            .text(slackContent)
            .build())
        .build());
    message.add(DividerBlock
        .builder()
        .build());
    ChatPostMessageRequest request = ChatPostMessageRequest.builder()
        .channel("slack-integration")
        .blocks(message)
        .build();
    MethodsClient methodsClient = slack.methods("******");
    ChatPostMessageResponse response = null;
    try {
        response = methodsClient.chatPostMessage(request);
    } catch (IOException e) {
        e.printStackTrace();
    } catch (SlackApiException e) {
        e.printStackTrace();
    }
    response.getChannel();
}
```

But getting below response: `ChatPostMessageResponse(**ok=false**, warning=null, **error=invalid_auth**, needed=null, provided=null, deprecatedArgument=null, responseMetadata=null, channel=null, ts=null, message=null)`.

So just want to know what is wrong with this code. I am not receiving any message. 
And how to integrate all desired steps (1-4) in this code snippet.

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
As `invalid_auth` indicates, an access token (bot token or user token) is missing or invalid. Make sure if your code uses a valid token for those API calls.

> MethodsClient methodsClient = slack.methods("******");

Particularly, please verify the `"******"` part in the code. I know you use a real token here but the value may be incorrect.

**Comment by AbhiInfy** [comment]
Thanks for the reply.
I have double-checked. My user token is correct. Do I need to provide any access right for it?

**Comment by seratch** [comment]
If your app doesn't have required scopes for it, you should get `missing_scope` error code instead. So, in this case, I think the lack of OAuth scopes is not the cause. I recommend testing with https://api.slack.com/methods/chat.postMessage/test to verify the token surely works.

**Comment by AbhiInfy** [comment]
Still getting below response:
{
    "ok": false,
    "error": "invalid_auth"
}
{Right now I m using Verification Token which is available under Basic Information with App Credentials(App ID, Client ID, Client Secret, Verification Token etc..)
I can see OAuth Access Token Under OAuth and Permission.
So which one need to use Verification Token or OAuth Access Token.

And with OAuth Access Token, getting below response:
ChatPostMessageResponse(ok=false, warning=null, error=missing_scope, needed=chat:write:bot, provided=admin,identify, deprecatedArgument=null, responseMetadata=null, channel=null, ts=null, message=null)

And with Verification Token, getting below response:
{
    "ok": false,
    "error": "invalid_auth"
}
    "ok": false,
    "error": "invalid_auth"
}

**Comment by seratch** [comment]
You cannot use a verification token for web api calls (it’s a legacy way to verify incoming requests from Slack). You need to use access tokens that start with xoxb- or xoxp-.

With an OAuth token, it seems you’ve got a missing_scope error. Please add chat:write scope and reinstall the app.

**Comment by AbhiInfy** [comment]
It's working fine. Thanks.
Now as discussed in the main query that I want to achieve the below steps:
1. Lookup user ID from email: https://api.slack.com/methods/users.lookupByEmail

2. Open DM with user: https://api.slack.com/methods/conversations.open

3. Send a message to the DM: https://api.slack.com/methods/chat.postMessage

4. May need to close the DM afterwards: https://api.slack.com/methods/conversations.close

And I am able to Test Step 1 and 3. But when executing 2nd Step I'm getting below error:
With user:
{
    "ok": false,
    "error": "user_not_found"
}

With Channel:
{
    "ok": false,
    "error": "channel_not_found"
}
I have already added scopes channels:write  groups:write  im:write  mpim:write
And I have taken user from Step 1. And also able to sent the message in Step 2 using that Channel.

**Comment by seratch** [comment]
As described in the API method documents, you need to add the following scopes for `users.lookupByEmail` and `conversations.open/close`.

* `users:read.email`
* `channels:manage`

**Comment by AbhiInfy** [comment]
but channels: manage is applicable for token type **bot** and I'm using Token type **user**
Right now I have below User Token scops:
channels:history, channels:read, channels:write, chat:write,  groups:write, im:write, mpim:write, users:read, users:read.email

**Comment by seratch** [comment]
All the APIs you mentioned are available for user tokens too. For step 2, send a valid list of user IDs to `conversations.open` API.

By the way, this issue tracker is for the ones specific to the Java SDK. Also, my main role here is to maintain better SDKs. So, (I hate to say this but) for general questions about Slack APIs, could you submit questions at https://my.slack.com/help/requests/new instead? Our developer support agents can answer your questions in a more timely manner. I'd appreciate it if you could understand this. 🙇

**Comment by AbhiInfy** [comment]
Thanks a lot for your kind support.
