### ISSUE TITLE
Missing import in Bolt for Java tutorial

### ISSUE THREAD

**Issue by gitmics** [slackapi/java-slack-sdk#536]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [x] Documentation

### Description

You are missing this import

```java
import com.slack.api.model.view.View;
```

---
(only for a bug report)

The issue is reproducible in:
* Module Version: **TODO**: x.y.z
* JDK Version: 
```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+14)
OpenJDK 64-Bit Server VM (build 14.0.1+14, mixed mode, sharing)
```
* OS Version etc: `MacOS 10.13.6 High Sierra`

The steps to reproduce are:
1.  Following the steps and Build the full example.
2. 
```
App.java:28: error: cannot find symbol
        View appHomeView = view(view -> view
        ^
  symbol:   class View
  location: class App
1 error
```
3.  Adding the import fixes the issue.
import com.slack.api.model.view.View;

The expected result is:

The code compiles with no errors

The actual result is:

```
App.java:28: error: cannot find symbol
        View appHomeView = view(view -> view
        ^
  symbol:   class View
  location: class App
1 error
```

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Thanks for taking the time to report this! I think you mention the page. Am I right? https://api.slack.com/start/building/bolt-java#listening If so, you're right. We'll fix the error soon.

**Comment by gitmics** [comment]
Yes, that was the page.
Sorry, meant to paste the URL into the bug report.
    On Friday, 7 August 2020, 10:34:12 BST, Kazuhiro Sera <notifications@github.com> wrote:  
 
 


Thanks for taking the time to report this! I think you mention the page. Am I right? https://api.slack.com/start/building/bolt-java#listening If so, you're right. We'll fix the error soon.

**Comment by seratch** [comment]
Thanks for reporting this. The page is now corrected.
